package negocio.basica;
// Generated 08/09/2011 20:33:14 by Hibernate Tools 3.2.0.CR1



/**
 * AgendaId generated by hbm2java
 */
public class AgendaId  implements java.io.Serializable {


     private int codAgenda;
     private int funcionarioPessoaCodPessoa;

    public AgendaId() {
    }

    public AgendaId(int codAgenda, int funcionarioPessoaCodPessoa) {
       this.codAgenda = codAgenda;
       this.funcionarioPessoaCodPessoa = funcionarioPessoaCodPessoa;
    }
   
    public int getCodAgenda() {
        return this.codAgenda;
    }
    
    public void setCodAgenda(int codAgenda) {
        this.codAgenda = codAgenda;
    }
    public int getFuncionarioPessoaCodPessoa() {
        return this.funcionarioPessoaCodPessoa;
    }
    
    public void setFuncionarioPessoaCodPessoa(int funcionarioPessoaCodPessoa) {
        this.funcionarioPessoaCodPessoa = funcionarioPessoaCodPessoa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AgendaId) ) return false;
		 AgendaId castOther = ( AgendaId ) other; 
         
		 return (this.getCodAgenda()==castOther.getCodAgenda())
 && (this.getFuncionarioPessoaCodPessoa()==castOther.getFuncionarioPessoaCodPessoa());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodAgenda();
         result = 37 * result + this.getFuncionarioPessoaCodPessoa();
         return result;
   }   


}


