package negocio.basica;
// Generated 08/09/2011 20:33:14 by Hibernate Tools 3.2.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Agenda generated by hbm2java
 */
public class Agenda  implements java.io.Serializable {


     private AgendaId id;
     private Funcionario funcionario;
     private Date dtentrada;
     private String hrentrada;
     private Date dtsaida;
     private String hrsaida;
     private Set statusAgendas = new HashSet(0);
     private Set servicos = new HashSet(0);

    public Agenda() {
    }

	
    public Agenda(AgendaId id, Funcionario funcionario, Date dtentrada, String hrentrada) {
        this.id = id;
        this.funcionario = funcionario;
        this.dtentrada = dtentrada;
        this.hrentrada = hrentrada;
    }
    public Agenda(AgendaId id, Funcionario funcionario, Date dtentrada, String hrentrada, Date dtsaida, String hrsaida, Set statusAgendas, Set servicos) {
       this.id = id;
       this.funcionario = funcionario;
       this.dtentrada = dtentrada;
       this.hrentrada = hrentrada;
       this.dtsaida = dtsaida;
       this.hrsaida = hrsaida;
       this.statusAgendas = statusAgendas;
       this.servicos = servicos;
    }
   
    public AgendaId getId() {
        return this.id;
    }
    
    public void setId(AgendaId id) {
        this.id = id;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Date getDtentrada() {
        return this.dtentrada;
    }
    
    public void setDtentrada(Date dtentrada) {
        this.dtentrada = dtentrada;
    }
    public String getHrentrada() {
        return this.hrentrada;
    }
    
    public void setHrentrada(String hrentrada) {
        this.hrentrada = hrentrada;
    }
    public Date getDtsaida() {
        return this.dtsaida;
    }
    
    public void setDtsaida(Date dtsaida) {
        this.dtsaida = dtsaida;
    }
    public String getHrsaida() {
        return this.hrsaida;
    }
    
    public void setHrsaida(String hrsaida) {
        this.hrsaida = hrsaida;
    }
    public Set getStatusAgendas() {
        return this.statusAgendas;
    }
    
    public void setStatusAgendas(Set statusAgendas) {
        this.statusAgendas = statusAgendas;
    }
    public Set getServicos() {
        return this.servicos;
    }
    
    public void setServicos(Set servicos) {
        this.servicos = servicos;
    }




}


