package negocio.basica;
// Generated 22/09/2011 20:48:05 by Hibernate Tools 3.2.0.CR1



/**
 * AnimalId generated by hbm2java
 */
public class AnimalId  implements java.io.Serializable {


     private int codAnimal;
     private int codPessoa;

    public AnimalId() {
    }

    public AnimalId(int codAnimal, int codPessoa) {
       this.codAnimal = codAnimal;
       this.codPessoa = codPessoa;
    }
   
    public int getCodAnimal() {
        return this.codAnimal;
    }
    
    public void setCodAnimal(int codAnimal) {
        this.codAnimal = codAnimal;
    }
    public int getCodPessoa() {
        return this.codPessoa;
    }
    
    public void setCodPessoa(int codPessoa) {
        this.codPessoa = codPessoa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AnimalId) ) return false;
		 AnimalId castOther = ( AnimalId ) other; 
         
		 return (this.getCodAnimal()==castOther.getCodAnimal())
 && (this.getCodPessoa()==castOther.getCodPessoa());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodAnimal();
         result = 37 * result + this.getCodPessoa();
         return result;
   }   


}


