package negocio.basica;
// Generated 08/09/2011 20:33:14 by Hibernate Tools 3.2.0.CR1



/**
 * ProdutoId generated by hbm2java
 */
public class ProdutoId  implements java.io.Serializable {


     private int codProduto;
     private int fornecedorPessoaCodPessoa;

    public ProdutoId() {
    }

    public ProdutoId(int codProduto, int fornecedorPessoaCodPessoa) {
       this.codProduto = codProduto;
       this.fornecedorPessoaCodPessoa = fornecedorPessoaCodPessoa;
    }
   
    public int getCodProduto() {
        return this.codProduto;
    }
    
    public void setCodProduto(int codProduto) {
        this.codProduto = codProduto;
    }
    public int getFornecedorPessoaCodPessoa() {
        return this.fornecedorPessoaCodPessoa;
    }
    
    public void setFornecedorPessoaCodPessoa(int fornecedorPessoaCodPessoa) {
        this.fornecedorPessoaCodPessoa = fornecedorPessoaCodPessoa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProdutoId) ) return false;
		 ProdutoId castOther = ( ProdutoId ) other; 
         
		 return (this.getCodProduto()==castOther.getCodProduto())
 && (this.getFornecedorPessoaCodPessoa()==castOther.getFornecedorPessoaCodPessoa());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodProduto();
         result = 37 * result + this.getFornecedorPessoaCodPessoa();
         return result;
   }   


}


