package negocio.basica;
// Generated 08/09/2011 20:33:14 by Hibernate Tools 3.2.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     private ProdutoId id;
     private Fornecedor fornecedor;
     private String nome;
     private String marca;
     private String grupo;
     private String unidade;
     private double peso;
     private String cor;
     private String lote;
     private Date dtvalidade;
     private double precovenda;
     private double precocompra;
     private Set servicos = new HashSet(0);

    public Produto() {
    }

	
    public Produto(ProdutoId id, Fornecedor fornecedor, String nome, String marca, String grupo, String unidade, double peso, String cor, String lote, Date dtvalidade, double precovenda, double precocompra) {
        this.id = id;
        this.fornecedor = fornecedor;
        this.nome = nome;
        this.marca = marca;
        this.grupo = grupo;
        this.unidade = unidade;
        this.peso = peso;
        this.cor = cor;
        this.lote = lote;
        this.dtvalidade = dtvalidade;
        this.precovenda = precovenda;
        this.precocompra = precocompra;
    }
    public Produto(ProdutoId id, Fornecedor fornecedor, String nome, String marca, String grupo, String unidade, double peso, String cor, String lote, Date dtvalidade, double precovenda, double precocompra, Set servicos) {
       this.id = id;
       this.fornecedor = fornecedor;
       this.nome = nome;
       this.marca = marca;
       this.grupo = grupo;
       this.unidade = unidade;
       this.peso = peso;
       this.cor = cor;
       this.lote = lote;
       this.dtvalidade = dtvalidade;
       this.precovenda = precovenda;
       this.precocompra = precocompra;
       this.servicos = servicos;
    }
   
    public ProdutoId getId() {
        return this.id;
    }
    
    public void setId(ProdutoId id) {
        this.id = id;
    }
    public Fornecedor getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(String grupo) {
        this.grupo = grupo;
    }
    public String getUnidade() {
        return this.unidade;
    }
    
    public void setUnidade(String unidade) {
        this.unidade = unidade;
    }
    public double getPeso() {
        return this.peso;
    }
    
    public void setPeso(double peso) {
        this.peso = peso;
    }
    public String getCor() {
        return this.cor;
    }
    
    public void setCor(String cor) {
        this.cor = cor;
    }
    public String getLote() {
        return this.lote;
    }
    
    public void setLote(String lote) {
        this.lote = lote;
    }
    public Date getDtvalidade() {
        return this.dtvalidade;
    }
    
    public void setDtvalidade(Date dtvalidade) {
        this.dtvalidade = dtvalidade;
    }
    public double getPrecovenda() {
        return this.precovenda;
    }
    
    public void setPrecovenda(double precovenda) {
        this.precovenda = precovenda;
    }
    public double getPrecocompra() {
        return this.precocompra;
    }
    
    public void setPrecocompra(double precocompra) {
        this.precocompra = precocompra;
    }
    public Set getServicos() {
        return this.servicos;
    }
    
    public void setServicos(Set servicos) {
        this.servicos = servicos;
    }




}


