package negocio.basica;
// Generated 22/09/2011 20:56:27 by Hibernate Tools 3.2.0.CR1



/**
 * ServicoHasProdutoId generated by hbm2java
 */
public class ServicoHasProdutoId  implements java.io.Serializable {


     private int servicoCodServico;
     private int produtoCodProduto;

    public ServicoHasProdutoId() {
    }

    public ServicoHasProdutoId(int servicoCodServico, int produtoCodProduto) {
       this.servicoCodServico = servicoCodServico;
       this.produtoCodProduto = produtoCodProduto;
    }
   
    public int getServicoCodServico() {
        return this.servicoCodServico;
    }
    
    public void setServicoCodServico(int servicoCodServico) {
        this.servicoCodServico = servicoCodServico;
    }
    public int getProdutoCodProduto() {
        return this.produtoCodProduto;
    }
    
    public void setProdutoCodProduto(int produtoCodProduto) {
        this.produtoCodProduto = produtoCodProduto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ServicoHasProdutoId) ) return false;
		 ServicoHasProdutoId castOther = ( ServicoHasProdutoId ) other; 
         
		 return (this.getServicoCodServico()==castOther.getServicoCodServico())
 && (this.getProdutoCodProduto()==castOther.getProdutoCodProduto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getServicoCodServico();
         result = 37 * result + this.getProdutoCodProduto();
         return result;
   }   


}


