package negocio.basica;
// Generated 22/09/2011 20:56:27 by Hibernate Tools 3.2.0.CR1



/**
 * ServicoHasAnimalId generated by hbm2java
 */
public class ServicoHasAnimalId  implements java.io.Serializable {


     private int servicoCodServico;
     private int animalCodAnimal;

    public ServicoHasAnimalId() {
    }

    public ServicoHasAnimalId(int servicoCodServico, int animalCodAnimal) {
       this.servicoCodServico = servicoCodServico;
       this.animalCodAnimal = animalCodAnimal;
    }
   
    public int getServicoCodServico() {
        return this.servicoCodServico;
    }
    
    public void setServicoCodServico(int servicoCodServico) {
        this.servicoCodServico = servicoCodServico;
    }
    public int getAnimalCodAnimal() {
        return this.animalCodAnimal;
    }
    
    public void setAnimalCodAnimal(int animalCodAnimal) {
        this.animalCodAnimal = animalCodAnimal;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ServicoHasAnimalId) ) return false;
		 ServicoHasAnimalId castOther = ( ServicoHasAnimalId ) other; 
         
		 return (this.getServicoCodServico()==castOther.getServicoCodServico())
 && (this.getAnimalCodAnimal()==castOther.getAnimalCodAnimal());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getServicoCodServico();
         result = 37 * result + this.getAnimalCodAnimal();
         return result;
   }   


}


