package negocio.basica;
// Generated 22/09/2011 20:56:27 by Hibernate Tools 3.2.0.CR1


import java.util.Date;

/**
 * Agenda generated by hbm2java
 */
public class Agenda  implements java.io.Serializable {


     private int codAgenda;
     private Funcionario funcionario;
     private Date dtentrada;
     private String hrentrada;
     private Date dtsaida;
     private String hrsaida;

    public Agenda() {
    }

	
    public Agenda(int codAgenda, Funcionario funcionario, Date dtentrada, String hrentrada) {
        this.codAgenda = codAgenda;
        this.funcionario = funcionario;
        this.dtentrada = dtentrada;
        this.hrentrada = hrentrada;
    }
    public Agenda(int codAgenda, Funcionario funcionario, Date dtentrada, String hrentrada, Date dtsaida, String hrsaida) {
       this.codAgenda = codAgenda;
       this.funcionario = funcionario;
       this.dtentrada = dtentrada;
       this.hrentrada = hrentrada;
       this.dtsaida = dtsaida;
       this.hrsaida = hrsaida;
    }
   
    public int getCodAgenda() {
        return this.codAgenda;
    }
    
    public void setCodAgenda(int codAgenda) {
        this.codAgenda = codAgenda;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Date getDtentrada() {
        return this.dtentrada;
    }
    
    public void setDtentrada(Date dtentrada) {
        this.dtentrada = dtentrada;
    }
    public String getHrentrada() {
        return this.hrentrada;
    }
    
    public void setHrentrada(String hrentrada) {
        this.hrentrada = hrentrada;
    }
    public Date getDtsaida() {
        return this.dtsaida;
    }
    
    public void setDtsaida(Date dtsaida) {
        this.dtsaida = dtsaida;
    }
    public String getHrsaida() {
        return this.hrsaida;
    }
    
    public void setHrsaida(String hrsaida) {
        this.hrsaida = hrsaida;
    }




}


