package negocio.basica;
// Generated 22/09/2011 20:56:27 by Hibernate Tools 3.2.0.CR1



/**
 * AgendaHasServico generated by hbm2java
 */
public class AgendaHasServico  implements java.io.Serializable {


     private AgendaHasServicoId id;
     private Servico servico;

    public AgendaHasServico() {
    }

    public AgendaHasServico(AgendaHasServicoId id, Servico servico) {
       this.id = id;
       this.servico = servico;
    }
   
    public AgendaHasServicoId getId() {
        return this.id;
    }
    
    public void setId(AgendaHasServicoId id) {
        this.id = id;
    }
    public Servico getServico() {
        return this.servico;
    }
    
    public void setServico(Servico servico) {
        this.servico = servico;
    }




}


