package negocio.basica;
// Generated 08/09/2011 20:33:14 by Hibernate Tools 3.2.0.CR1



/**
 * AnimalId generated by hbm2java
 */
public class AnimalId  implements java.io.Serializable {


     private int codAnimal;
     private int pessoaCodPessoa;

    public AnimalId() {
    }

    public AnimalId(int codAnimal, int pessoaCodPessoa) {
       this.codAnimal = codAnimal;
       this.pessoaCodPessoa = pessoaCodPessoa;
    }
   
    public int getCodAnimal() {
        return this.codAnimal;
    }
    
    public void setCodAnimal(int codAnimal) {
        this.codAnimal = codAnimal;
    }
    public int getPessoaCodPessoa() {
        return this.pessoaCodPessoa;
    }
    
    public void setPessoaCodPessoa(int pessoaCodPessoa) {
        this.pessoaCodPessoa = pessoaCodPessoa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AnimalId) ) return false;
		 AnimalId castOther = ( AnimalId ) other; 
         
		 return (this.getCodAnimal()==castOther.getCodAnimal())
 && (this.getPessoaCodPessoa()==castOther.getPessoaCodPessoa());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodAnimal();
         result = 37 * result + this.getPessoaCodPessoa();
         return result;
   }   


}


