package negocio.basica;
// Generated 08/09/2011 20:33:14 by Hibernate Tools 3.2.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private int pessoaCodPessoa;
     private Pessoa pessoa;
     private String matricula;
     private String login;
     private String senha;
     private String nome;
     private String cpf;
     private String rg;
     private Date datanasc;
     private Set atendentes = new HashSet(0);
     private Set agendas = new HashSet(0);
     private Set veterinarios = new HashSet(0);
     private Set servicos = new HashSet(0);

    public Funcionario() {
    }

	
    public Funcionario(int pessoaCodPessoa, Pessoa pessoa, String matricula, String login, String senha, String nome, String cpf, String rg, Date datanasc) {
        this.pessoaCodPessoa = pessoaCodPessoa;
        this.pessoa = pessoa;
        this.matricula = matricula;
        this.login = login;
        this.senha = senha;
        this.nome = nome;
        this.cpf = cpf;
        this.rg = rg;
        this.datanasc = datanasc;
    }
    public Funcionario(int pessoaCodPessoa, Pessoa pessoa, String matricula, String login, String senha, String nome, String cpf, String rg, Date datanasc, Set atendentes, Set agendas, Set veterinarios, Set servicos) {
       this.pessoaCodPessoa = pessoaCodPessoa;
       this.pessoa = pessoa;
       this.matricula = matricula;
       this.login = login;
       this.senha = senha;
       this.nome = nome;
       this.cpf = cpf;
       this.rg = rg;
       this.datanasc = datanasc;
       this.atendentes = atendentes;
       this.agendas = agendas;
       this.veterinarios = veterinarios;
       this.servicos = servicos;
    }
   
    public int getPessoaCodPessoa() {
        return this.pessoaCodPessoa;
    }
    
    public void setPessoaCodPessoa(int pessoaCodPessoa) {
        this.pessoaCodPessoa = pessoaCodPessoa;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }
    public Date getDatanasc() {
        return this.datanasc;
    }
    
    public void setDatanasc(Date datanasc) {
        this.datanasc = datanasc;
    }
    public Set getAtendentes() {
        return this.atendentes;
    }
    
    public void setAtendentes(Set atendentes) {
        this.atendentes = atendentes;
    }
    public Set getAgendas() {
        return this.agendas;
    }
    
    public void setAgendas(Set agendas) {
        this.agendas = agendas;
    }
    public Set getVeterinarios() {
        return this.veterinarios;
    }
    
    public void setVeterinarios(Set veterinarios) {
        this.veterinarios = veterinarios;
    }
    public Set getServicos() {
        return this.servicos;
    }
    
    public void setServicos(Set servicos) {
        this.servicos = servicos;
    }




}


