package negocio.basica;
// Generated 22/09/2011 20:56:27 by Hibernate Tools 3.2.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pessoa generated by hbm2java
 */
public class Pessoa  implements java.io.Serializable {


     private int codPessoa;
     private String endereco;
     private String numero;
     private String complemento;
     private String bairro;
     private String cidade;
     private String cep;
     private String uf;
     private String telefone1;
     private String telefone2;
     private String email;
     private Date datacad;
     private String grupo;
     private Set funcionarios = new HashSet(0);
     private Set animals = new HashSet(0);
     private Set clientefs = new HashSet(0);
     private Set fornecedors = new HashSet(0);
     private Set clientejs = new HashSet(0);

    public Pessoa() {
    }

	
    public Pessoa(int codPessoa, String endereco, String numero, String bairro, String cidade, String cep, String uf, String telefone1, String email, Date datacad, String grupo) {
        this.codPessoa = codPessoa;
        this.endereco = endereco;
        this.numero = numero;
        this.bairro = bairro;
        this.cidade = cidade;
        this.cep = cep;
        this.uf = uf;
        this.telefone1 = telefone1;
        this.email = email;
        this.datacad = datacad;
        this.grupo = grupo;
    }
    public Pessoa(int codPessoa, String endereco, String numero, String complemento, String bairro, String cidade, String cep, String uf, String telefone1, String telefone2, String email, Date datacad, String grupo, Set funcionarios, Set animals, Set clientefs, Set fornecedors, Set clientejs) {
       this.codPessoa = codPessoa;
       this.endereco = endereco;
       this.numero = numero;
       this.complemento = complemento;
       this.bairro = bairro;
       this.cidade = cidade;
       this.cep = cep;
       this.uf = uf;
       this.telefone1 = telefone1;
       this.telefone2 = telefone2;
       this.email = email;
       this.datacad = datacad;
       this.grupo = grupo;
       this.funcionarios = funcionarios;
       this.animals = animals;
       this.clientefs = clientefs;
       this.fornecedors = fornecedors;
       this.clientejs = clientejs;
    }
   
    public int getCodPessoa() {
        return this.codPessoa;
    }
    
    public void setCodPessoa(int codPessoa) {
        this.codPessoa = codPessoa;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }
    public String getTelefone1() {
        return this.telefone1;
    }
    
    public void setTelefone1(String telefone1) {
        this.telefone1 = telefone1;
    }
    public String getTelefone2() {
        return this.telefone2;
    }
    
    public void setTelefone2(String telefone2) {
        this.telefone2 = telefone2;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getDatacad() {
        return this.datacad;
    }
    
    public void setDatacad(Date datacad) {
        this.datacad = datacad;
    }
    public String getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(String grupo) {
        this.grupo = grupo;
    }
    public Set getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set funcionarios) {
        this.funcionarios = funcionarios;
    }
    public Set getAnimals() {
        return this.animals;
    }
    
    public void setAnimals(Set animals) {
        this.animals = animals;
    }
    public Set getClientefs() {
        return this.clientefs;
    }
    
    public void setClientefs(Set clientefs) {
        this.clientefs = clientefs;
    }
    public Set getFornecedors() {
        return this.fornecedors;
    }
    
    public void setFornecedors(Set fornecedors) {
        this.fornecedors = fornecedors;
    }
    public Set getClientejs() {
        return this.clientejs;
    }
    
    public void setClientejs(Set clientejs) {
        this.clientejs = clientejs;
    }




}


