package negocio.basica;
// Generated 22/09/2011 20:54:50 by Hibernate Tools 3.2.0.CR1



/**
 * ProdutoId generated by hbm2java
 */
public class ProdutoId  implements java.io.Serializable {


     private int codProduto;
     private int fornecedorCodPessoa;

    public ProdutoId() {
    }

    public ProdutoId(int codProduto, int fornecedorCodPessoa) {
       this.codProduto = codProduto;
       this.fornecedorCodPessoa = fornecedorCodPessoa;
    }
   
    public int getCodProduto() {
        return this.codProduto;
    }
    
    public void setCodProduto(int codProduto) {
        this.codProduto = codProduto;
    }
    public int getFornecedorCodPessoa() {
        return this.fornecedorCodPessoa;
    }
    
    public void setFornecedorCodPessoa(int fornecedorCodPessoa) {
        this.fornecedorCodPessoa = fornecedorCodPessoa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProdutoId) ) return false;
		 ProdutoId castOther = ( ProdutoId ) other; 
         
		 return (this.getCodProduto()==castOther.getCodProduto())
 && (this.getFornecedorCodPessoa()==castOther.getFornecedorCodPessoa());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodProduto();
         result = 37 * result + this.getFornecedorCodPessoa();
         return result;
   }   


}


