package negocio.basica;
// Generated 22/09/2011 20:56:27 by Hibernate Tools 3.2.0.CR1



/**
 * ServicoHasProduto generated by hbm2java
 */
public class ServicoHasProduto  implements java.io.Serializable {


     private ServicoHasProdutoId id;
     private Servico servico;

    public ServicoHasProduto() {
    }

    public ServicoHasProduto(ServicoHasProdutoId id, Servico servico) {
       this.id = id;
       this.servico = servico;
    }
   
    public ServicoHasProdutoId getId() {
        return this.id;
    }
    
    public void setId(ServicoHasProdutoId id) {
        this.id = id;
    }
    public Servico getServico() {
        return this.servico;
    }
    
    public void setServico(Servico servico) {
        this.servico = servico;
    }




}


