package negocio.basica;
// Generated 22/09/2011 20:56:27 by Hibernate Tools 3.2.0.CR1



/**
 * ServicoHasAnimal generated by hbm2java
 */
public class ServicoHasAnimal  implements java.io.Serializable {


     private ServicoHasAnimalId id;
     private Servico servico;

    public ServicoHasAnimal() {
    }

    public ServicoHasAnimal(ServicoHasAnimalId id, Servico servico) {
       this.id = id;
       this.servico = servico;
    }
   
    public ServicoHasAnimalId getId() {
        return this.id;
    }
    
    public void setId(ServicoHasAnimalId id) {
        this.id = id;
    }
    public Servico getServico() {
        return this.servico;
    }
    
    public void setServico(Servico servico) {
        this.servico = servico;
    }




}


