package negocio.basica;
// Generated 22/09/2011 20:56:27 by Hibernate Tools 3.2.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * Servico generated by hbm2java
 */
public class Servico  implements java.io.Serializable {


     private int codServico;
     private String descricao;
     private String duracao;
     private double valor;
     private Set funcionarios = new HashSet(0);
     private Set servicoHasProdutos = new HashSet(0);
     private Set agendaHasServicos = new HashSet(0);
     private Set servicoHasAnimals = new HashSet(0);

    public Servico() {
    }

	
    public Servico(int codServico, String descricao, String duracao, double valor) {
        this.codServico = codServico;
        this.descricao = descricao;
        this.duracao = duracao;
        this.valor = valor;
    }
    public Servico(int codServico, String descricao, String duracao, double valor, Set funcionarios, Set servicoHasProdutos, Set agendaHasServicos, Set servicoHasAnimals) {
       this.codServico = codServico;
       this.descricao = descricao;
       this.duracao = duracao;
       this.valor = valor;
       this.funcionarios = funcionarios;
       this.servicoHasProdutos = servicoHasProdutos;
       this.agendaHasServicos = agendaHasServicos;
       this.servicoHasAnimals = servicoHasAnimals;
    }
   
    public int getCodServico() {
        return this.codServico;
    }
    
    public void setCodServico(int codServico) {
        this.codServico = codServico;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getDuracao() {
        return this.duracao;
    }
    
    public void setDuracao(String duracao) {
        this.duracao = duracao;
    }
    public double getValor() {
        return this.valor;
    }
    
    public void setValor(double valor) {
        this.valor = valor;
    }
    public Set getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set funcionarios) {
        this.funcionarios = funcionarios;
    }
    public Set getServicoHasProdutos() {
        return this.servicoHasProdutos;
    }
    
    public void setServicoHasProdutos(Set servicoHasProdutos) {
        this.servicoHasProdutos = servicoHasProdutos;
    }
    public Set getAgendaHasServicos() {
        return this.agendaHasServicos;
    }
    
    public void setAgendaHasServicos(Set agendaHasServicos) {
        this.agendaHasServicos = agendaHasServicos;
    }
    public Set getServicoHasAnimals() {
        return this.servicoHasAnimals;
    }
    
    public void setServicoHasAnimals(Set servicoHasAnimals) {
        this.servicoHasAnimals = servicoHasAnimals;
    }




}


