package negocio.basica;
// Generated 22/09/2011 20:56:27 by Hibernate Tools 3.2.0.CR1



/**
 * StatusAgendaId generated by hbm2java
 */
public class StatusAgendaId  implements java.io.Serializable {


     private int codStatus;
     private int agendaCodAgenda;
     private String descricao;

    public StatusAgendaId() {
    }

    public StatusAgendaId(int codStatus, int agendaCodAgenda, String descricao) {
       this.codStatus = codStatus;
       this.agendaCodAgenda = agendaCodAgenda;
       this.descricao = descricao;
    }
   
    public int getCodStatus() {
        return this.codStatus;
    }
    
    public void setCodStatus(int codStatus) {
        this.codStatus = codStatus;
    }
    public int getAgendaCodAgenda() {
        return this.agendaCodAgenda;
    }
    
    public void setAgendaCodAgenda(int agendaCodAgenda) {
        this.agendaCodAgenda = agendaCodAgenda;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StatusAgendaId) ) return false;
		 StatusAgendaId castOther = ( StatusAgendaId ) other; 
         
		 return (this.getCodStatus()==castOther.getCodStatus())
 && (this.getAgendaCodAgenda()==castOther.getAgendaCodAgenda())
 && ( (this.getDescricao()==castOther.getDescricao()) || ( this.getDescricao()!=null && castOther.getDescricao()!=null && this.getDescricao().equals(castOther.getDescricao()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodStatus();
         result = 37 * result + this.getAgendaCodAgenda();
         result = 37 * result + ( getDescricao() == null ? 0 : this.getDescricao().hashCode() );
         return result;
   }   


}


