package negocio.basica;
// Generated 22/09/2011 20:56:27 by Hibernate Tools 3.2.0.CR1



/**
 * StatusAgenda generated by hbm2java
 */
public class StatusAgenda  implements java.io.Serializable {


     private StatusAgendaId id;

    public StatusAgenda() {
    }

    public StatusAgenda(StatusAgendaId id) {
       this.id = id;
    }
   
    public StatusAgendaId getId() {
        return this.id;
    }
    
    public void setId(StatusAgendaId id) {
        this.id = id;
    }




}


