package negocio.basica;
// Generated 08/09/2011 20:33:14 by Hibernate Tools 3.2.0.CR1



/**
 * StatusAgendaId generated by hbm2java
 */
public class StatusAgendaId  implements java.io.Serializable {


     private int codStatus;
     private int agendaCodAgenda;
     private int agendaFuncionarioPessoaCodPessoa;

    public StatusAgendaId() {
    }

    public StatusAgendaId(int codStatus, int agendaCodAgenda, int agendaFuncionarioPessoaCodPessoa) {
       this.codStatus = codStatus;
       this.agendaCodAgenda = agendaCodAgenda;
       this.agendaFuncionarioPessoaCodPessoa = agendaFuncionarioPessoaCodPessoa;
    }
   
    public int getCodStatus() {
        return this.codStatus;
    }
    
    public void setCodStatus(int codStatus) {
        this.codStatus = codStatus;
    }
    public int getAgendaCodAgenda() {
        return this.agendaCodAgenda;
    }
    
    public void setAgendaCodAgenda(int agendaCodAgenda) {
        this.agendaCodAgenda = agendaCodAgenda;
    }
    public int getAgendaFuncionarioPessoaCodPessoa() {
        return this.agendaFuncionarioPessoaCodPessoa;
    }
    
    public void setAgendaFuncionarioPessoaCodPessoa(int agendaFuncionarioPessoaCodPessoa) {
        this.agendaFuncionarioPessoaCodPessoa = agendaFuncionarioPessoaCodPessoa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StatusAgendaId) ) return false;
		 StatusAgendaId castOther = ( StatusAgendaId ) other; 
         
		 return (this.getCodStatus()==castOther.getCodStatus())
 && (this.getAgendaCodAgenda()==castOther.getAgendaCodAgenda())
 && (this.getAgendaFuncionarioPessoaCodPessoa()==castOther.getAgendaFuncionarioPessoaCodPessoa());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodStatus();
         result = 37 * result + this.getAgendaCodAgenda();
         result = 37 * result + this.getAgendaFuncionarioPessoaCodPessoa();
         return result;
   }   


}


