package negocio.basica;
// Generated 08/09/2011 20:33:14 by Hibernate Tools 3.2.0.CR1



/**
 * StatusAgenda generated by hbm2java
 */
public class StatusAgenda  implements java.io.Serializable {


     private StatusAgendaId id;
     private Agenda agenda;
     private String descricao;

    public StatusAgenda() {
    }

    public StatusAgenda(StatusAgendaId id, Agenda agenda, String descricao) {
       this.id = id;
       this.agenda = agenda;
       this.descricao = descricao;
    }
   
    public StatusAgendaId getId() {
        return this.id;
    }
    
    public void setId(StatusAgendaId id) {
        this.id = id;
    }
    public Agenda getAgenda() {
        return this.agenda;
    }
    
    public void setAgenda(Agenda agenda) {
        this.agenda = agenda;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }




}


